{
    "summary": "id",
    "description": "Path parameter",
    "get": {
        "tags": [
            "movies"
        ],
        "responses": {
            "200": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "integer"
                        },
                        "examples": {
                            "id": {
                                "value": {
                                    "id": 1,
                                    "name": "The Matrix",
                                    "price": 12.99
                                }
                            }
                        }
                    }
                },
                "description": "Full details of the movie."
            },
            "404": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "integer"
                        },
                        "examples": {
                            "id": {
                                "value": {
                                    "error": "Error message."
                                }
                            }
                        }
                    }
                },
                "description": "Movie was not found in movies array."
            }
        },
        "summary": "Get details of a specific movie.",
        "description": "Returns the details of a movie by its ID."
    },
    "parameters": [
        {
            "name": "id",
            "description": "PATH PARAMETER",
            "schema": {
                "type": "integer"
            },
            "in": "path",
            "required": true
        }
    ]
}